apiVersion: v1
kind: Service
metadata:
  name: discovery-postgres
  namespace: ns-discovery
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    k8s-app: discovery-postgres
