apiVersion: v1
kind: ConfigMap
metadata:
  name: discovery-config
  namespace: ns-discovery
data:
  # Environment
  DISCOVERY_DEVELOPMENT_MODE: "true"

  # Metabase
  MB_DB_FILE: "/tmp/metabase.db"
  MB_DB_SSL: "false"
  MB_DB_TYPE: "postgres"
  MB_DB_URL: "postgreseos-primary.eos-core:5432"
  MB_DB_DBNAME: "discovery"
  MB_DB_USER: "discovery"
  MB_JDBC_PARAMETERS: "prepareThreshold=0"
  MB_INIT_ADMIN_USER: "demo"
  MB_INIT_ADMIN_MAIL: "demo@stratio.com"
  MB_INIT_ADMIN_PASSWORD: "123456"

  # NGINX
  PROXY_READ_TIMEOUT: "120"

  # TODO: SSO
  USE_GOSEC_SSO_AUTH: "false"
  #SSO_URI: ""

  # TODO: Security
  #VAULT_HOST: ""
  #VAULT_PORT: ""
  #APPROLENAME: ""
  #CALICO_NETWORK: ""

  #Logs
  API_LOG_LEVEL: "INFO"
  DRIVER_LOG_LEVEL: "INFO"
  FIELDVALUES_LOG_LEVEL: "INFO"
  MIDDLEWARE_LOG_LEVEL: "INFO"
  MCHANGE_LOG_LEVEL: "INFO"
  SERVICE_LOG_LEVEL: "INFO"
  METABASE_LOG_LEVEL: "INFO"
  SYNC_LOG_LEVEL: "INFO"
  QUERYPROCESSORPERMISIONS_LOG_LEVEL: "INFO"
  NGINX_ERROR_LOG_LEVEL: "debug"

  # Discovery CI/CD
  DISCOVERY_CICD_AKKA_REQUEST_TIMEOUT: "30s"
  DISCOVERY_CICD_API_METABASE_TIMEOUT: "20s"
  #DISCOVERY_CICD_JAVA_OPTIONS: ""


  # TODO: Others:
  #DISCOVERY_POSTGRES_SERVICE_ID: ""
  #DISCOVERY_INSTANCE_NAME: ""
  #SERVICE_URL: ""
  #NETWORK_SEGMENTATION: ""
  #USE_DYNAMIC_AUTHENTICATION: ""
  #STRATIO_ABSOLUTE_MAX_RESULTS: ""
