kind: Deployment
apiVersion: apps/v1
metadata:
  name: discovery-demo
  namespace: ns-discovery
  labels:
    k8s-app: discovery-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: discovery-demo # defines how deployment finds which Pods to manage
  template:
    metadata:
      name: discovery-demo
      labels:
        k8s-app: discovery-demo
        cluster-name: discovery-demo
    spec:
      containers:
        - name: discovery-demo
          image: 'qa.int.stratio.com/stratio/discovery:0.40.0-SNAPSHOT'
          imagePullPolicy: IfNotPresent # (other values: Always, Never)
          resources:
            requests:
              cpu: '1'
              memory: 2Gi
            limits:
              cpu: '1'
              memory: 2Gi
          #env:
            # The Kubernetes API discovery will use this service name to look for
            # nodes with this value in the 'app' label.
            # This can be customized with the 'pod-label-selector' setting.
          #  - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
          #    valueFrom:
          #      fieldRef:
          #        apiVersion: v1
          #        fieldPath: "metadata.labels['cluster-name']"
          command: ["/bin/bash"]
          args: ["/app/bin/start"]
          envFrom:
            - configMapRef:
                name: discovery-config
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            privileged: false
          ports:
            - name: discoveryapi
              containerPort: 3000
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /api/health
          #    port: discoveryapi
          #    scheme: HTTP
          #  periodSeconds: 30
          #  timeoutSeconds: 15
          #  successThreshold: 1
          #  failureThreshold: 10 # TODO enable startupProbe & set failureThreshold to 3
          #readinessProbe:
          #  httpGet:
          #    path: /api/health
          #    port: discoveryapi
          #    scheme: HTTP
          #  periodSeconds: 15
          #  timeoutSeconds: 15
          #  successThreshold: 1
          #  failureThreshold: 10 # TODO enable startupProbe & set failureThreshold to 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600