apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  namespace: ns-discovery
subsets:
  - addresses:
      - ip: 10.0.2.2
      # Driver docker -> - ip: 172.17.0.1
      # Driver virtualbox -> - ip: 10.0.2.2
    ports:
      - port: 5432
